version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - observability

  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev -- --host
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - observability


  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ecocharger
      POSTGRES_USER: ecocharger
      POSTGRES_PASSWORD: ecocharger
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ecocharger"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - observability

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    command:
      - --web.enable-remote-write-receiver
      - --enable-feature=native-histograms
      - --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml
    networks:
      - observability

  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3005:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./config/grafana:/etc/grafana/provisioning/
    networks:
      - observability

volumes:
  postgres-data:


networks:
  observability:
  default:
    name: default_network
