version: "3.8"

services:
  backend:
    build: ./EcoCharger/backend
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 15
    networks:
      - observability

  frontend:
    build: ./EcoCharger/frontend
    ports:
      - "5000:5000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev -- --host
    volumes:
      - ./EcoCharger/frontend:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - observability



  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ecocharger
      POSTGRES_USER: ecocharger
      POSTGRES_PASSWORD: ecocharger
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ecocharger"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - observability

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - observability
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      prometheus:
        condition: service_started
      backend:
        condition: service_healthy
    networks:
      - observability
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_SERVER_ROOT_URL=https://localhost:3000/
      - GF_SERVER_HTTP_PORT=3000



volumes:
  postgres-data:
  grafana-storage:


networks:
  observability:
  default:
    name: default_network
