import React from 'react';

// This file was generated by AI

// BREAKS: react/no-multi-comp
class BadComponent extends React.Component {
  // BREAKS: react/forbid-prop-types (uses object)
  static propTypes = {
    data: React.PropTypes.object, // deprecated and forbidden
  };

  // BREAKS: react/no-is-mounted
  componentDidMount() {
    if (this.isMounted()) {
      console.log('Mounted!');
    }
  }

  render() {
    return (
      <div>
        {/* BREAKS: jsx-a11y/alt-text */}
        <img src="logo.png" />

        {/* BREAKS: react/jsx-boolean-value (should be 'visible' not 'visible={true}') */}
        <span hidden={false} visible={true}>Hello!</span>

        {/* BREAKS: react/jsx-no-bind (binding in JSX) */}
        <button onClick={this.handleClick.bind(this)}>Click</button>

        {/* BREAKS: react/no-string-refs */}
        <input ref="myInput" />

        {/* BREAKS: react/no-array-index-key */}
        {[1, 2, 3].map((n, i) => <div key={i}>{n}</div>)}
      </div>
    );
  }

  handleClick() {
    alert('Clicked');
  }
}

// Additional component in same file
// BREAKS: react/no-multi-comp
const ExtraComponent = () => <p>Another Component</p>;

export default BadComponent;
