name: Test and Analyze Spring Boot Project

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-sonar:
    name: Build and Analyze with SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # --- Build Docker images ---
      - name: Build Docker images
        run: docker compose build
        working-directory: .

      # --- Start all Docker containers ---
      - name: Start Docker containers
        run: docker compose up -d
        working-directory: .

      # --- (Optional) Wait for services to be ready ---
      - name: Wait for containers to be ready
        run: sleep 20  # Replace with health checks or wait-for-it if needed

      - name: Build and run tests
        run: mvn clean verify
        working-directory: ./backend

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        with:
          projectBaseDir: ./backend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_SCANNER_OPTS: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.java.binaries=target/classes

      # --- (Optional) Stop containers after build ---
      - name: Stop Docker containers
        if: always()
        run: docker compose down
        working-directory: ./backend
